-**first line**  
    +*second in first*  
    +*third in first*   

In [2]:
import numpy as np

In [17]:
ls_1 = [1,2,3,4,5]
ls_2 = [5,4,3,2,1]
ls_3 = [-1, -2, -3 , -4]

arr = np.array([ls_1, ls_2], dtype = 'int64')
arr_2 = np.array([[[-1,1],[-2,2]],[[-3, 3], [-4, 4]]], dtype = 'int64')
print(f'{arr_2}\n{type(arr_2)}\n{arr_2.dtype}\n{     arr_2.ndim, arr_2.shape, arr_2.size, arr_2.dtype, arr_2.itemsize, arr_2.nbytes     }\n')

print(f'{arr}\n{type(arr)}\n{      arr.ndim, arr.shape, arr.size, arr.dtype, arr.itemsize, arr.nbytes       }')



[[[-1  1]
  [-2  2]]

 [[-3  3]
  [-4  4]]]
<class 'numpy.ndarray'>
int64
(3, (2, 2, 2), 8, dtype('int64'), 8, 64)

[[1 2 3 4 5]
 [5 4 3 2 1]]
<class 'numpy.ndarray'>
(2, (2, 5), 10, dtype('int64'), 8, 80)


In [4]:
ones = np.ones(shape = (3,2, 2))
#print(ones)
diag_one = np.eye(4,4)
#print(diag_one)
arange = np.arange(2, 20, 2)         #   (start, upto, spacing)
print(arange)
linspace = np.linspace(10, 20, 30)       #   (start, end, elem_count)
print(linspace)
print(np.count_nonzero(linspace))

[ 2  4  6  8 10 12 14 16 18]
[10.         10.34482759 10.68965517 11.03448276 11.37931034 11.72413793
 12.06896552 12.4137931  12.75862069 13.10344828 13.44827586 13.79310345
 14.13793103 14.48275862 14.82758621 15.17241379 15.51724138 15.86206897
 16.20689655 16.55172414 16.89655172 17.24137931 17.5862069  17.93103448
 18.27586207 18.62068966 18.96551724 19.31034483 19.65517241 20.        ]
30


In [186]:
from io import StringIO
x = StringIO('''88.25 93.45 72.60 90.90
72.3 78.85 92.15 65.75
90.5 92.45 89.25 94.50
''')
d = np.loadtxt(x, delimiter = ' ')
print(d)

[[88.25 93.45 72.6  90.9 ]
 [72.3  78.85 92.15 65.75]
 [90.5  92.45 89.25 94.5 ]]


--Define a random 3-D array x4 of shape (3, 4, 2) and of numbers between 0 and 1.

--Simulate a random normal distribution of 20 elements, whose mean is 5 and standard deviation 2.5 . Capture the result in x5. 

In [317]:
rand = np.random.rand(3 ,4, 2)
#print(rand)
np.random.seed(100)
value = np.random.randn(20)        #     generates randome distribution of mean 0 and standard deviation 1
np.random.seed(100)
normal = np.random.normal(size = 20, loc = 5, scale = 2.5)
print(f'normal_distribution by np.random.normal: \n{normal}\n')
normal = 5 + 2.5 * value
print(f'normal_distribution by np.random.randn() and (mean + S.D.* val): \n{normal}\n')

normal_distribution by np.random.normal: 
[0.62558632 5.85670101 7.88258951 4.36890991 7.45330197 6.2855471
 5.55294917 2.32489167 4.52626042 5.63750361 3.85493254 6.08790872
 3.54101237 7.04211768 6.68180201 4.73897214 3.67179906 7.57433171
 3.90466094 2.20420438]

normal_distribution by np.random.randn() and (mean + S.D.* val): 
[0.62558632 5.85670101 7.88258951 4.36890991 7.45330197 6.2855471
 5.55294917 2.32489167 4.52626042 5.63750361 3.85493254 6.08790872
 3.54101237 7.04211768 6.68180201 4.73897214 3.67179906 7.57433171
 3.90466094 2.20420438]



In [445]:
np.random.seed(100)
x = np.random.randint(10, 100, 10 )
print(x)
print(   x.reshape(2,5)   )
print(   x.reshape(2,1,5)   )    #    two arrays of 1x5  (3-D array)

[18 34 77 97 89 58 20 62 63 76]
[[18 34 77 97 89]
 [58 20 62 63 76]]
[[[18 34 77 97 89]]

 [[58 20 62 63 76]]]


Create a ndarray x having first 20 natural numbers, using arange method.

Determine the shape of x.

Change the shape of x to (2, 10) and assign it to new array y.

Split the array y horizontally in to two arrays.

Now, Change the shape of x to (4, 5) and assign it to new array z.

Split the array z vertically in to two arrays

Create a 2-D array p, of shape (2, 2) with elements 3, 6, 9, 12.

Create a 2-D array q, of shape (2, 3) with elements 15, 18, 21, 24, 27, 30.

Join the two arrays p and q horizontally.

In [42]:
x = np.arange(1,21, 1) 
print(f'x: {x}, {x.shape}')
y = x.reshape(2,10)
print(f'x.reshape(2,10): {y}, {y.shape}]\n')

hy = np.hsplit(y, 2)
print(hy)
z = x.reshape(4,5)
print(z)
vz = np.vsplit(z, 2)
print(vz)

p = np.arange(3, 19, 3)
q = np.arange(15, 31, 3)
print(f'\n{p}\n{q}\n')

pq_hjoin = np.hstack((p, q))
print(pq_hjoin, '\n')
pq_vjoin = np.vstack((p,q))
print(pq_vjoin)

x: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20], (20,)
x.reshape(2,10): [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]], (2, 10)]

[array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]]), array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]

[ 3  6  9 12 15 18]
[15 18 21 24 27 30]

[ 3  6  9 12 15 18 15 18 21 24 27 30] 

[[ 3  6  9 12 15 18]
 [15 18 21 24 27 30]]


In [458]:
a = np.arange(1,10).reshape(3,3)
print(a)
print(a.sum(axis = 0))
print(a.sum(axis = 1))
vals = np.array([1, np.nan, 3,4])
print(vals.sum())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]
nan


In [513]:
a, b = np.arange(0, 10, 2), np.arange(1, 10, 2)
print(f'a = {a}\t\tb = {b}')
print(f'a**2 = {a**2}')
print(f'np.sqrt(val) = {np.sqrt(a).round(2)}')
print(f'np.multiply(vals) = {np.multiply(a,b)}')
print(f'a+b = {a+b}')         # everything is element-wise
print(f'a.min = {a.min()}')
print(f'a.mean() = {a.mean()}')
print(f'a.st. dev =  {a.std()}')
print(f'a.var = {a.var()}')

a = [0 2 4 6 8]		b = [1 3 5 7 9]
a**2 = [ 0  4 16 36 64]
np.sqrt(val) = [0.   1.41 2.   2.45 2.83]
np.multiply(vals) = [ 0  6 20 42 72]
a+b = [ 1  5  9 13 17]
a.min = 0
a.mean() = 4.0
a.st. dev =  2.8284271247461903
a.var = 8.0


#### Indexing and Slicing

In [537]:
#  1-D ndarray
x = np.arange(10)
print(f'{   x   }\n{   x[3]   }\n{   x[2:4]   }')
print(x[2:6:3])   # starts from 2 followed by 3 spaces till 6 (excluding it just like normal indexing)

[0 1 2 3 4 5 6 7 8 9]
3
[2 3]
[2 5]


In [641]:
# 2-D ndarray
y = np.arange(0,20).reshape(2,10)
print(y)
print(  y[:, 5:8]  )
print(  y[1:, 4:]  )
print(  y[1][4:] )        #  [][]  is used for indexing not useful for slicing
print(  y[1:, 7:10]  )    #  print(  y[1:2, 7:10] )
print(  y[:, 7]  )
print(  y[:, 7:8]  )


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 5  6  7]
 [15 16 17]]
[[14 15 16 17 18 19]]
[14 15 16 17 18 19]
[[17 18 19]]
[ 7 17]
17
[[ 7]
 [17]]


In [649]:
# 3-D ndarray
z = np.array([[[-1, 1], [-2, 2]],
              [[-4, 4], [-5, 5]],
              [[-7, 7], [-9, 9]]])
print(  z[1, :, 1]  )        #   takes second row,  including all elems in that row,   filter only second columns in sub arr.
print(  z[1:, 1, :]  )
print(  z[2, :, :]  )   #  z[2]
print([z[0, 1, 0]]+[z[2, 0, 0]])


[4 5]
[[-5  5]
 [-9  9]]
[[-7  7]
 [-9  9]]
[-2, -7]


In [664]:
for i in y:
    print(i)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [661]:
for i in np.nditer(z):      # for accessing each and every element in a numpy array
    print(i, end = ' ')

-1 1 -2 2 -4 4 -5 5 -7 7 -9 9 

In [674]:
# boolean indexing ,  just like pandas
print(  y % 2 == 0  )
print(  y[y % 2 == 0 ]  )
print(  z[z<0]  )

[[ True False  True False  True False  True False  True False]
 [ True False  True False  True False  True False  True False]]
[ 0  2  4  6  8 10 12 14 16 18]
[-1 -2 -4 -5 -7 -9]
